x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

services:
  rosbot-xl:
    image: husarion/rosbot-xl:humble
    container_name: rosbot_xl
    <<: *net-config
    command: >
      ros2 launch rosbot_xl_bringup bringup.launch.py
        mecanum:=False

  rosbot-xl-imu-data:
    image: husarion/rosbot-xl-manipulation:humble-1.1.0-20230621-stable
    <<: *net-config
    command: >
      ros2 topic pub /_imu/data_raw "sensor_msgs/msg/Imu"
        "{header: {stamp: {sec: 0, nanosec: 0}, frame_id: ''}, orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}, orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], angular_velocity: {x: 0.0, y: 0.0, z: 0.0}, angular_velocity_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], linear_acceleration: {x: 0.0, y: 0.0, z: 0.0}, linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}" 

  rosbridge:
    image: husarion/rosbridge-server:humble-1.3.1-20230831
    <<: *net-config
    ports:
      - 9090:9090
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml use_compression:=true

  foxglove:
    image: husarion/foxglove:1.72.0
    ports:
      - 8080:8080
    volumes:
      - ./config/foxglove.json:/foxglove/default-layout.json
    environment:
      - DS_TYPE=rosbridge-websocket
      - DS_PORT=9090
      - UI_PORT=8080
